apiVersion: v1
kind: Service
metadata:
  name: hello-devops-world-service
spec:
  type: NodePort
  selector:
    app: hello-devops-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
