name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Using Docker access token here

      - name: Build the Docker image
        run: docker build -t hello-devops-world .

      - name: Run the Docker container
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: docker run -d -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -p 80:80 hello-devops-world

      # Optional: Check if the container is running correctly by printing the logs
      - name: Check Docker container logs
        run: docker logs $(docker ps -lq)

      # Run Playwright tests when CI pipeline is triggered
      - name: Run Playwright Tests
        run: npx playwright test
