name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Ensure you're using a Node.js version that works with Playwright

      - name: Install dependencies
        run: npm install

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Using Docker access token here

      - name: Build the Docker image
        run: docker build -t hello-devops-world .

      - name: Start Docker container for testing
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: docker run -d -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -p 8000:80 hello-devops-world # Exposing port 8000 for Playwright tests

      - name: Run Playwright tests
        run: npx playwright test

      - name: Tear down Docker container after tests
        run: docker stop $(docker ps -q --filter ancestor=hello-devops-world) # Stop the container after tests

      # Optional: Check if the container is running correctly by printing the logs
      - name: Check Docker container logs
        run: docker logs $(docker ps -lq)

      - name: Run final Docker container (for deployment or further testing)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: docker run -d -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -p 80:80 hello-devops-world
